import Head from 'next/head'

import styled from 'styled-components'

export const Title = styled.div`
  font: ${props => props.theme.text.title.h1.regular_poppins};
`

const Home: React.FC = () => {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Title>hi there</Title>
      </main>
    </div>
  )
}

export default Home
